#!/usr/bin/env bash
set -e
set -x

wordpress_dir=$(pwd)

wordpress_install() {
  wp config create \
      --allow-root \
      --path="$wordpress_dir" \
      --dbhost="${WORDPRESS_DB_HOST:=mysql}" \
      --dbuser="${WORDPRESS_DB_USER:=root}" \
      --dbpass="${WORDPRESS_DB_PASSWORD:=}" \
      --dbname="${WORDPRESS_DB_NAME:=wordpress}" \
      --extra-php <<PHP
define( 'WP_SITEURL', 'http://' . \$_SERVER['HTTP_HOST'] );
define( 'WP_HOME', 'http://' . \$_SERVER['HTTP_HOST'] );

define( 'WP_MEMORY_LIMIT', '64M' );
PHP

  wp core install \
      --allow-root \
      --url="localhost" \
      --title="${WORDPRESS_TITLE:=blog}" \
      --admin_user="${WORDPRESS_ADMIN_USER:=admin}" \
      --admin_password="${WORDPRESS_ADMIN_PASSWORD:=admin}" \
      --admin_email="${WORDPRESS_ADMIN_EMAIL:=admin@example.com}" \
      --skip-email

  wp plugin uninstall \
    akismet \
    hello \
    --allow-root

  chown -R www-data:www-data "$wordpress_dir"
}

if ! [ -e wp-config.php ]; then
  wordpress_install
fi

exec "$@"
